---
- name: Checking that both or none proxysql_cluster_username & proxysql_cluster_password are defined
  fail:
    msg: "proxysql_cluster_username & proxysql_cluster_password must be both set or false"
  when: proxysql_cluster_username != proxysql_cluster_password and (proxysql_cluster_password == False or proxysql_cluster_username == False)
