---
- name: Adds repository key
  apt_key:
    url: http://repo.proxysql.com/ProxySQL/repo_pub_key
    state: present

- name: Adds percona repositories
  apt:
    deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
  register: adds_percona_repositories

- name: Installs proxysql & python-mysqldb
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - proxysql2
    - python3-pymysql
    - python-pymysql
  when: adds_percona_repositories

- name: Installs mysql-common & client
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - mysql-common
    - mysql-client

- name: Configures proxysql
  template:
    src: "proxysql.{{ proxysql_mysql_server_type }}.cnf.j2"
    dest: /etc/proxysql.cnf
    mode: 0644
    backup: true
  notify:
    - Load config from file to memory

- name: Setup proxysql global variables
  proxysql_global_variables:
    login_user: "{{ proxysql_admin_user }}"
    login_password: "{{ proxysql_admin_password }}"
    variable: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items: "{{ proxysql_global_variables }}"

- name: Ensures proxysql is started
  service:
    name: proxysql
    state: started
    enabled: yes

- name: Creates log dir
  file:
    path: /var/log/proxysql/
    state: directory

- name: Adds logrotate
  template:
    src: proxysql.logrotate.conf.j2
    dest: /etc/logrotate.d/proxysql
    mode: 0644
